/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicExpertisesRouteImport } from './routes/_public/expertises'
import { Route as PublicMentionsLegalesRouteImport } from './routes/_public/mentions-legales'
import { Route as PublicPartenairesRouteImport } from './routes/_public/partenaires'
import { Route as PublicPolitiqueConfidentialiteRouteImport } from './routes/_public/politique-confidentialite'
import { Route as PublicRealisationsRouteImport } from './routes/_public/realisations'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminProfilRouteImport } from './routes/admin/profil'
import { Route as PublicBlogIndexRouteImport } from './routes/_public/blog/index'
import { Route as PublicBlogSlugRouteImport } from './routes/_public/blog/$slug'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminBlogNewRouteImport } from './routes/admin/blog.new'
import { Route as PublicPoleSlugIndexRouteImport } from './routes/_public/pole/$slug/index'
import { Route as PublicPoleSlugSubSlugRouteImport } from './routes/_public/pole/$slug/$subSlug'
import { Route as AdminBlogIdEditRouteImport } from './routes/admin/blog.$id.edit'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicExpertisesRoute = PublicExpertisesRouteImport.update({
  id: '/expertises',
  path: '/expertises',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMentionsLegalesRoute = PublicMentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPartenairesRoute = PublicPartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPolitiqueConfidentialiteRoute =
  PublicPolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicRealisationsRoute = PublicRealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => PublicRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfilRoute = AdminProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AdminRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AdminRoute,
} as any)
const PublicPoleSlugIndexRoute = PublicPoleSlugIndexRouteImport.update({
  id: '/pole/$slug/',
  path: '/pole/$slug/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPoleSlugSubSlugRoute = PublicPoleSlugSubSlugRouteImport.update({
  id: '/pole/$slug/$subSlug',
  path: '/pole/$slug/$subSlug',
  getParentRoute: () => PublicRoute,
} as any)
const AdminBlogIdEditRoute = AdminBlogIdEditRouteImport.update({
  id: '/blog/$id/edit',
  path: '/blog/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contact': typeof PublicContactRoute
  '/expertises': typeof PublicExpertisesRoute
  '/mentions-legales': typeof PublicMentionsLegalesRoute
  '/partenaires': typeof PublicPartenairesRoute
  '/politique-confidentialite': typeof PublicPolitiqueConfidentialiteRoute
  '/realisations': typeof PublicRealisationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/profil': typeof AdminProfilRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/pole/$slug/$subSlug': typeof PublicPoleSlugSubSlugRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/pole/$slug/': typeof PublicPoleSlugIndexRoute
}
export interface FileRoutesByTo {
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contact': typeof PublicContactRoute
  '/expertises': typeof PublicExpertisesRoute
  '/mentions-legales': typeof PublicMentionsLegalesRoute
  '/partenaires': typeof PublicPartenairesRoute
  '/politique-confidentialite': typeof PublicPolitiqueConfidentialiteRoute
  '/realisations': typeof PublicRealisationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/profil': typeof AdminProfilRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/blog': typeof PublicBlogIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/pole/$slug/$subSlug': typeof PublicPoleSlugSubSlugRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/pole/$slug': typeof PublicPoleSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/expertises': typeof PublicExpertisesRoute
  '/_public/mentions-legales': typeof PublicMentionsLegalesRoute
  '/_public/partenaires': typeof PublicPartenairesRoute
  '/_public/politique-confidentialite': typeof PublicPolitiqueConfidentialiteRoute
  '/_public/realisations': typeof PublicRealisationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/profil': typeof AdminProfilRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/_public/pole/$slug/$subSlug': typeof PublicPoleSlugSubSlugRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/_public/pole/$slug/': typeof PublicPoleSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/contact'
    | '/expertises'
    | '/mentions-legales'
    | '/partenaires'
    | '/politique-confidentialite'
    | '/realisations'
    | '/admin/login'
    | '/admin/profil'
    | '/admin/'
    | '/blog/$slug'
    | '/admin/blog/new'
    | '/blog/'
    | '/admin/blog/'
    | '/pole/$slug/$subSlug'
    | '/admin/blog/$id/edit'
    | '/pole/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/rss.xml'
    | '/sitemap.xml'
    | '/contact'
    | '/expertises'
    | '/mentions-legales'
    | '/partenaires'
    | '/politique-confidentialite'
    | '/realisations'
    | '/admin/login'
    | '/admin/profil'
    | '/'
    | '/admin'
    | '/blog/$slug'
    | '/admin/blog/new'
    | '/blog'
    | '/admin/blog'
    | '/pole/$slug/$subSlug'
    | '/admin/blog/$id/edit'
    | '/pole/$slug'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/_public/contact'
    | '/_public/expertises'
    | '/_public/mentions-legales'
    | '/_public/partenaires'
    | '/_public/politique-confidentialite'
    | '/_public/realisations'
    | '/admin/login'
    | '/admin/profil'
    | '/_public/'
    | '/admin/'
    | '/_public/blog/$slug'
    | '/admin/blog/new'
    | '/_public/blog/'
    | '/admin/blog/'
    | '/_public/pole/$slug/$subSlug'
    | '/admin/blog/$id/edit'
    | '/_public/pole/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/expertises': {
      id: '/_public/expertises'
      path: '/expertises'
      fullPath: '/expertises'
      preLoaderRoute: typeof PublicExpertisesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/mentions-legales': {
      id: '/_public/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof PublicMentionsLegalesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/partenaires': {
      id: '/_public/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PublicPartenairesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/politique-confidentialite': {
      id: '/_public/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PublicPolitiqueConfidentialiteRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/realisations': {
      id: '/_public/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof PublicRealisationsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profil': {
      id: '/admin/profil'
      path: '/profil'
      fullPath: '/admin/profil'
      preLoaderRoute: typeof AdminProfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/pole/$slug/': {
      id: '/_public/pole/$slug/'
      path: '/pole/$slug'
      fullPath: '/pole/$slug/'
      preLoaderRoute: typeof PublicPoleSlugIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pole/$slug/$subSlug': {
      id: '/_public/pole/$slug/$subSlug'
      path: '/pole/$slug/$subSlug'
      fullPath: '/pole/$slug/$subSlug'
      preLoaderRoute: typeof PublicPoleSlugSubSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/blog/$id/edit': {
      id: '/admin/blog/$id/edit'
      path: '/blog/$id/edit'
      fullPath: '/admin/blog/$id/edit'
      preLoaderRoute: typeof AdminBlogIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface PublicRouteChildren {
  PublicContactRoute: typeof PublicContactRoute
  PublicExpertisesRoute: typeof PublicExpertisesRoute
  PublicMentionsLegalesRoute: typeof PublicMentionsLegalesRoute
  PublicPartenairesRoute: typeof PublicPartenairesRoute
  PublicPolitiqueConfidentialiteRoute: typeof PublicPolitiqueConfidentialiteRoute
  PublicRealisationsRoute: typeof PublicRealisationsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
  PublicPoleSlugSubSlugRoute: typeof PublicPoleSlugSubSlugRoute
  PublicPoleSlugIndexRoute: typeof PublicPoleSlugIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicContactRoute: PublicContactRoute,
  PublicExpertisesRoute: PublicExpertisesRoute,
  PublicMentionsLegalesRoute: PublicMentionsLegalesRoute,
  PublicPartenairesRoute: PublicPartenairesRoute,
  PublicPolitiqueConfidentialiteRoute: PublicPolitiqueConfidentialiteRoute,
  PublicRealisationsRoute: PublicRealisationsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBlogSlugRoute: PublicBlogSlugRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
  PublicPoleSlugSubSlugRoute: PublicPoleSlugSubSlugRoute,
  PublicPoleSlugIndexRoute: PublicPoleSlugIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProfilRoute: typeof AdminProfilRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminBlogIdEditRoute: typeof AdminBlogIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminProfilRoute: AdminProfilRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminBlogIdEditRoute: AdminBlogIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
